var goodsSchema = `CREATE TABLE goods (
    user_id text PRIMARY KEY,
    list_goods jsonb[] NOT NULL
) ;`;

var skuSchema = `CREATE TABLE IF NOT EXISTS skus (
    sku_id integer NOT NULL,
    sku_name text NOT NULL,
    price real NOT NULL,
    discount real NOT NULL CHECK (discount > 0),
    discounted_price real NOT NULL,
    club_discounted_price real NOT NULL,
    last_fetch bigint NOT NULL,
    last_cost_price real NOT NULL,
    disabled boolean NOT NULL,
    deleted boolean NOT NULL
    --generated jsonb GENERATED BY DEFAULT SELECT qty + tax FROM sku_metrics
    ) ;`;

var skuJsonSchema = `CREATE TABLE IF NOT EXISTS skus_json (
    sku_id integer NOT NULL,
    sku_name text NOT NULL,
    price real NOT NULL,
    discount real NOT NULL CHECK (discount > 0),
    discounted_price real NOT NULL,
    club_discounted_price real NOT NULL,
    last_fetch bigint NOT NULL,
    last_cost_price real NOT NULL,
    disabled boolean NOT NULL,
    deleted boolean NOT NULL,
    metrics jsonb
) ;`;

var skuMetricsSchema = `CREATE TABLE IF NOT EXISTS sku_metrics (
    sku_id integer NOT NULL,
    sku_name text NOT NULL,
    year integer NOT NULL DEFAULT 0,
    qty integer NOT NULL DEFAULT 0,
    tax real NOT NULL DEFAULT 0,
    fines real NOT NULL DEFAULT 0,
    net_profit real NOT NULL DEFAULT 0,
    margin real NOT NULL DEFAULT 0,
    retail_amount real NOT NULL DEFAULT 0,
    return_amount real NOT NULL DEFAULT 0,
    storage_cost real NOT NULL DEFAULT 0,
    delivery_cost real NOT NULL DEFAULT 0,
    acceptance real NOT NULL DEFAULT 0,
    insurance_fee real NOT NULL DEFAULT 0,
    other_expenses real NOT NULL DEFAULT 0,
    taxable_amount real NOT NULL DEFAULT 0,
    seller_payout_amount real NOT NULL DEFAULT 0,
    deduction_or_payment real NOT NULL DEFAULT 0,
    additional_insurance_fee real NOT NULL DEFAULT 0
    ) ;`;

export { skuJsonSchema, skuMetricsSchema, skuSchema };
