var users = `CREATE TABLE IF NOT EXISTS users (
                                            user_id varchar(20) PRIMARY KEY, 
                                            login text NOT NULL DEFAULT '', 
                                            passwd text NOT NULL DEFAULT '', 
                                            role text NOT NULL DEFAULT 'user',
                                            data integer NOT NULL DEFAULT 0
                                            );`;

var tokens = `CREATE TABLE IF NOT EXISTS tokens (
                                            user_id varchar(20) PRIMARY KEY, 
                                            token text NOT NULL DEFAULT ''
                                            ) ;`;

var weekly_prices_and_discounts = `CREATE TABLE IF NOT EXISTS weekly_prices_and_discounts (
                                            user_id varchar(20) PRIMARY KEY, 
                                            upload_id integer NOT NULL DEFAULT 0, 
                                            weekly_prices_and_discounts json[] NOT NULL DEFAULT '{}'
                                            ) ;`;

var tax_params = `CREATE TABLE IF NOT EXISTS tax_params (
                                            user_id varchar(20) PRIMARY KEY,
                                            year smallint NOT NULL DEFAULT ${new Date().getFullYear()},
                                            tax_rate smallint NOT NULL DEFAULT 6,
                                            paid_taxAmount numeric NOT NULL DEFAULT 0,
                                            mandatory_insurance_fee smallint NOT NULL DEFAULT 0,
                                            insurance_fee_percentage smallint NOT NULL DEFAULT 10,
                                            paid_insurance_fee numeric NOT NULL DEFAULT 0,
                                            retail_amount numeric NOT NULL DEFAULT 0,
                                            taxable_amount numeric NOT NULL DEFAULT 0,
                                            final_profit numeric NOT NULL DEFAULT 0,
                                            is_insurance_fee_paid boolean NOT NULL DEFAULT false,
                                            additional_insurance_fee numeric NOT NULL DEFAULT 0,
                                            requires_additional_insurance_fee boolean NOT NULL DEFAULT false,
                                            excess_income_for_additional_insurance_fee smallint NOT NULL DEFAULT 0,
                                            has_excess_income_for_insurance boolean NOT NULL DEFAULT false,
                                            mandatory_insurance_fee_is_paid boolean NOT NULL DEFAULT false,
                                            additional_insurance_fee_is_paid boolean NOT NULL DEFAULT false,
                                            excess_insurance_rate smallint NOT NULL DEFAULT 0,
                                            schema_version smallint NOT NULL DEFAULT 1
                                            ) ;`;

var reports_trees = `CREATE TABLE IF NOT EXISTS reports_trees ( 
                                            user_id varchar(20) PRIMARY KEY, 
                                            years json[] NOT NULL DEFAULT '{}', 
                                            schema_version smallint NOT NULL DEFAULT 1
                                            ) ;`;

var goods = `CREATE TABLE IF NOT EXISTS goods (
                                            user_id varchar(20) NOT NULL,
                                            id integer NOT NULL DEFAULT 0,
                                            sku_name text NOT NULL DEFAULT '',
                                            price numeric NOT NULL DEFAULT 0,
                                            discount numeric NOT NULL DEFAULT 0,
                                            discounted_price numeric NOT NULL DEFAULT 0,
                                            club_discounted_price numeric NOT NULL DEFAULT 0,
                                            disabled boolean NOT NULL DEFAULT false,
                                            last_fetch bigint NOT NULL DEFAULT 0,  --${new Date(Date.now() + 3 * 60 * 60 * 1000)},
                                            last_updated bigint NOT NULL DEFAULT 0,
                                            last_cost_price numeric NOT NULL DEFAULT 0,
                                            is_price_updated boolean NOT NULL DEFAULT false,
                                            error_text text NOT NULL DEFAULT '',
                                            deleted boolean NOT NULL DEFAULT false,
                                            metrics json[] NOT NULL DEFAULT '{}'
                                            ) ; `;

var reports = `CREATE TABLE IF NOT EXISTS reports (
                                            user_id varchar(20) NOT NULL DEFAULT '',
                                            report_id integer PRIMARY KEY,
                                            schema_version smallint NOT NULL DEFAULT 1,
                                            date_from varchar(10) NOT NULL DEFAULT '',
                                            date_to varchar(10) NOT NULL DEFAULT '',
                                            total_sold integer NOT NULL DEFAULT 0,
                                            total_fines numeric NOT NULL DEFAULT 0,
                                            total_product_costs numeric NOT NULL DEFAULT 0,
                                            total_return_amount numeric NOT NULL DEFAULT 0,
                                            total_delivery_cost numeric NOT NULL DEFAULT 0,
                                            total_storage_cost numeric NOT NULL DEFAULT 0,
                                            total_retail_amount numeric NOT NULL DEFAULT 0,
                                            total_paid_acceptance numeric NOT NULL DEFAULT 0,
                                            total_advertising_costs numeric NOT NULL DEFAULT 0,
                                            total_deduction_or_payment numeric NOT NULL DEFAULT 0,
                                            total_additional_payment numeric NOT NULL DEFAULT 0,
                                            total_tax_amount numeric NOT NULL DEFAULT 0,
                                            total_insurance_fee numeric NOT NULL DEFAULT 0,
                                            total_additional_insurance_fee numeric NOT NULL DEFAULT 0,
                                            total_other_expenses numeric NOT NULL DEFAULT 0,
                                            total_taxable_amount numeric NOT NULL DEFAULT 0,
                                            total_profit numeric NOT NULL DEFAULT 0,
                                            total_pre_tax_profit numeric NOT NULL DEFAULT 0,
                                            total_final_profit numeric NOT NULL DEFAULT 0,
                                            total_profit_margin numeric NOT NULL DEFAULT 0,
                                            tax_rate smallint NOT NULL DEFAULT 6,
                                            buyback_report_is_exist boolean NOT NULL DEFAULT false,
                                            crosses_tax_years boolean NOT NULL DEFAULT false,   
                                            recorded_to jsonb,
                                            total_seller_payout_amount numeric NOT NULL DEFAULT 0,
                                            total_seller_payout_amount_of_start_year numeric NOT NULL DEFAULT 0,
                                            total_seller_payout_amount_of_end_year numeric NOT NULL DEFAULT 0,
                                            is_finances_accounted boolean NOT NULL DEFAULT false,
                                            total_sold_of_start_year integer NOT NULL DEFAULT 0,
                                            total_fines_of_start_year numeric NOT NULL DEFAULT 0,
                                            total_product_costs_of_start_year numeric NOT NULL DEFAULT 0,
                                            total_return_amount_of_start_year integer NOT NULL DEFAULT 0,
                                            total_delivery_cost_of_start_year numeric NOT NULL DEFAULT 0,
                                            total_storage_cost_of_start_year numeric NOT NULL DEFAULT 0,
                                            total_retail_amount_of_start_year numeric NOT NULL DEFAULT 0,
                                            total_paid_acceptance_of_start_year numeric NOT NULL DEFAULT 0,
                                            total_advertising_costs_of_start_year numeric NOT NULL DEFAULT 0,
                                            total_deduction_or_payment_of_start_year numeric NOT NULL DEFAULT 0,
                                            total_additional_payment_of_start_year numeric NOT NULL DEFAULT 0,
                                            total_tax_amount_of_start_year numeric NOT NULL DEFAULT 0,
                                            total_insurance_fee_of_start_year numeric NOT NULL DEFAULT 0,
                                            total_additional_insurance_fee_of_start_year numeric NOT NULL DEFAULT 0,
                                            total_other_expenses_of_start_year numeric NOT NULL DEFAULT 0,
                                            total_taxable_amount_of_start_year numeric NOT NULL DEFAULT 0,
                                            total_profit_of_start_year numeric NOT NULL DEFAULT 0,
                                            total_pre_tax_profit_of_start_year numeric NOT NULL DEFAULT 0,
                                            total_final_profit_of_start_year numeric NOT NULL DEFAULT 0,
                                            total_profit_margin_of_start_year numeric NOT NULL DEFAULT 0,
                                            total_sold_of_end_year numeric NOT NULL DEFAULT 0,
                                            total_fines_of_end_year numeric NOT NULL DEFAULT 0,
                                            total_product_costs_of_end_year numeric NOT NULL DEFAULT 0,
                                            total_return_amount_of_end_year numeric NOT NULL DEFAULT 0,
                                            total_delivery_cost_of_end_year numeric NOT NULL DEFAULT 0,
                                            total_storage_cost_of_end_year numeric NOT NULL DEFAULT 0,
                                            total_retail_amount_of_end_year numeric NOT NULL DEFAULT 0,
                                            total_paid_acceptance_of_end_year numeric NOT NULL DEFAULT 0,
                                            total_advertising_costs_of_end_year numeric NOT NULL DEFAULT 0,
                                            total_deduction_or_payment_of_end_year numeric NOT NULL DEFAULT 0,
                                            total_additional_payment_of_end_year numeric NOT NULL DEFAULT 0,
                                            total_tax_amount_of_end_year numeric NOT NULL DEFAULT 0,
                                            total_insurance_fee_of_end_year numeric NOT NULL DEFAULT 0,
                                            total_additional_insurance_fee_of_end_year numeric NOT NULL DEFAULT 0,
                                            total_other_expenses_of_end_year numeric NOT NULL DEFAULT 0,
                                            total_taxable_amount_of_end_year numeric NOT NULL DEFAULT 0,
                                            total_profit_of_end_year numeric NOT NULL DEFAULT 0,
                                            total_pre_tax_profit_of_end_year numeric NOT NULL DEFAULT 0,
                                            total_final_profit_ofendt_year numeric NOT NULL DEFAULT 0,
                                            total_profit_margin_of_end_year numeric NOT NULL DEFAULT 0,
                                            skus json NOT NULL DEFAULT '{}'
                                            ) ;`;

var skus = `CREATE TABLE IF NOT EXISTS skus (
                                            user_id varchar(20) NOT NULL,
                                            report_id integer NOT NULL,
                                            sku_id  integer NOT NULL DEFAULT 0,
                                            sku_name text NOT NULL,
                                            qty integer NOT NULL DEFAULT 0,
                                            qty_of_start_year integer NOT NULL DEFAULT 0,
                                            qty_of_end_year integer NOT NULL DEFAULT 0,
                                            taxable_amount numeric NOT NULL DEFAULT 0,
                                            taxable_amount_of_start_year numeric NOT NULL DEFAULT 0,
                                            taxable_amount_of_end_year numeric NOT NULL DEFAULT 0,
                                            cost_price numeric NOT NULL DEFAULT 0,
                                            other_expenses numeric NOT NULL DEFAULT 0,
                                            other_expenses_of_start_year numeric NOT NULL DEFAULT 0,
                                            other_expenses_of_end_year numeric NOT NULL DEFAULT 0,
                                            seller_payout_amount numeric NOT NULL DEFAULT 0,
                                            seller_payout_amount_of_start_year numeric NOT NULL DEFAULT 0,
                                            seller_payout_amount_of_end_year numeric NOT NULL DEFAULT 0,
                                            fines numeric NOT NULL DEFAULT 0,
                                            fines_of_start_year numeric NOT NULL DEFAULT 0,
                                            fines_of_end_year numeric NOT NULL DEFAULT 0,
                                            return_amount numeric NOT NULL DEFAULT 0,
                                            return_amount_of_start_year numeric NOT NULL DEFAULT 0,
                                            return_amount_of_end_year numeric NOT NULL DEFAULT 0,
                                            retail_amount numeric NOT NULL DEFAULT 0,
                                            retail_amount_of_start_year numeric NOT NULL DEFAULT 0,
                                            retail_amount_of_end_year numeric NOT NULL DEFAULT 0,
                                            delivery_cost numeric NOT NULL DEFAULT 0,
                                            delivery_cost_of_start_year numeric NOT NULL DEFAULT 0,
                                            delivery_cost_of_end_year numeric NOT NULL DEFAULT 0,
                                            storage_cost numeric NOT NULL DEFAULT 0,
                                            storage_cost_of_start_year numeric NOT NULL DEFAULT 0,
                                            storage_cost_of_year_year numeric NOT NULL DEFAULT 0,
                                            additional_payment numeric NOT NULL DEFAULT 0,
                                            additional_payment_of_start_year numeric NOT NULL DEFAULT 0,
                                            additional_payment_of_end_year numeric NOT NULL DEFAULT 0,
                                            acceptance numeric NOT NULL DEFAULT 0,
                                            acceptance_of_start_year numeric NOT NULL DEFAULT 0,
                                            acceptance_of_end_year numeric NOT NULL DEFAULT 0,
                                            deduction_or_payment numeric NOT NULL DEFAULT 0,
                                            deduction_or_payment_of_start_year numeric NOT NULL DEFAULT 0,
                                            deduction_or_payment_of_end_year numeric NOT NULL DEFAULT 0,
                                            insurance_fee numeric NOT NULL DEFAULT 0,
                                            insurance_fee_of_start_year numeric NOT NULL DEFAULT 0,
                                            insurance_fee_of_end_year numeric NOT NULL DEFAULT 0,
                                            additional_insurance_fee numeric NOT NULL DEFAULT 0,
                                            additional_insurance_fee_of_start_year numeric NOT NULL DEFAULT 0,
                                            additional_insurance_fee_of_end_year numeric NOT NULL DEFAULT 0,
                                            profit numeric NOT NULL DEFAULT 0,
                                            profit_of_start_year numeric NOT NULL DEFAULT 0,
                                            profit_of_end_year numeric NOT NULL DEFAULT 0,
                                            pre_tax_profit numeric NOT NULL DEFAULT 0,
                                            pre_tax_profit_of_start_year numeric NOT NULL DEFAULT 0,
                                            pre_tax_profit_of_end_year numeric NOT NULL DEFAULT 0,
                                            is_cost_price_set boolean NOT NULL DEFAULT false,
                                            profit_margin numeric NOT NULL DEFAULT 0,
                                            profit_margin_of_start_year numeric NOT NULL DEFAULT 0,
                                            profit_margin_of_end_year numeric NOT NULL DEFAULT 0,
                                            final_profit numeric NOT NULL DEFAULT 0,
                                            final_profit_of_start_year numeric NOT NULL DEFAULT 0,
                                            final_profit_of_end_year numeric NOT NULL DEFAULT 0,
                                            tax numeric NOT NULL DEFAULT 0,
                                            tax_of_start_year numeric NOT NULL DEFAULT 0,
                                            tax_of_end_year numeric NOT NULL DEFAULT 0,
                                            is_insurance_fee_included boolean NOT NULL DEFAULT false,
                                            is_insurance_fee_included_of_start_year boolean NOT NULL DEFAULT false,
                                            is_insurance_fee_included_of_end_year boolean NOT NULL DEFAULT false,
                                            schema_version smallint NOT NULL DEFAULT 1
                                            )`;

export default [
  skus,
  goods,
  reports,
  tax_params,
  tokens,
  weekly_prices_and_discounts,
  users,
  reports_trees,
];
